[versions]

aap-core = "0.8.0"
aap-lv2 = "0.3.0"

accompanist-drawablepainter = "0.30.1"
accompanist-permissions = "0.30.1"
agp = "8.1.4"
kotlin = "1.8.10"
ndk = "26.1.10909125"
cmake = "3.22.1"
build-tools = "33.0.1"
dokka = "1.8.20"
compose = "1.4.3"
androidx-test = "1.5.0"
coroutines = "1.7.3"

[libraries]

aap-core = { module = "org.androidaudioplugin:androidaudioplugin", version.ref = "aap-core" }
aap-midi-device-service = { module = "org.androidaudioplugin:androidaudioplugin-midi-device-service", version.ref = "aap-core" }
aap-ui-compose = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose", version.ref = "aap-core" }
aap-ui-compose-app = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose-app", version.ref = "aap-core" }
aap-ui-web = { module = "org.androidaudioplugin:androidaudioplugin-ui-web", version.ref = "aap-core" }
aap-testing = { module = "org.androidaudioplugin:androidaudioplugin-testing", version.ref = "aap-core" }

aap-lv2 = { module = "org.androidaudioplugin:androidaudioplugin-lv2", version.ref = "aap-lv2" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist-drawablepainter" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
compose-audio-controls = { module = "org.androidaudioplugin:compose-audio-controls", version = "0.2.0" }

tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2023.08.00" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.4" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

preference-ktx = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
libcxx-provider = { module = "dev.atsushieno:libcxx-provider", version.ref = "ndk" }

lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version = "2.6.2" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.2" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.0" }
webkit = { module = "androidx.webkit:webkit", version = "1.8.0" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version = "1.5.4" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

junit = { module = "junit:junit", version = "4.13.2" }
test-core = { module =  "androidx.test:core", version.ref = "androidx-test" }
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

ktmidi = { module = "dev.atsushieno:ktmidi", version = "0.6.0" }

oboe = { module = "com.google.oboe:oboe", version = "1.8.0" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3" }
[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
