[versions]

aap-core = "0.8.0"
aap-lv2 = "0.3.0"

accompanist-drawablepainter = "0.32.0"
accompanist-permissions = "0.32.0"
agp = "8.2.2" #"8.4.0-alpha07"
kotlin = "1.9.21"
ndk = "26.1.10909125"
cmake = "3.22.1"
build-tools = "33.0.1"
dokka = "1.9.10"
compose = "1.6.0"
compose-compiler = "1.5.6"
androidx-test = "1.5.0"
coroutines = "1.8.0-RC2"

[libraries]

aap-core = { module = "org.androidaudioplugin:androidaudioplugin", version.ref = "aap-core" }
aap-midi-device-service = { module = "org.androidaudioplugin:androidaudioplugin-midi-device-service", version.ref = "aap-core" }
aap-ui-compose = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose", version.ref = "aap-core" }
aap-ui-compose-app = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose-app", version.ref = "aap-core" }
aap-ui-web = { module = "org.androidaudioplugin:androidaudioplugin-ui-web", version.ref = "aap-core" }
aap-testing = { module = "org.androidaudioplugin:androidaudioplugin-testing", version.ref = "aap-core" }

aap-lv2 = { module = "org.androidaudioplugin:androidaudioplugin-lv2", version.ref = "aap-lv2" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist-drawablepainter" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
compose-audio-controls = { module = "org.androidaudioplugin:compose-audio-controls", version = "0.2.0" }

tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2024.01.00" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.6" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

preference-ktx = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
libcxx-provider = { module = "dev.atsushieno:libcxx-provider", version.ref = "ndk" }

lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version = "2.7.0" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.7.0" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }
webkit = { module = "androidx.webkit:webkit", version = "1.10.0" }

junit = { module = "junit:junit", version = "4.13.2" }
test-core = { module =  "androidx.test:core", version.ref = "androidx-test" }
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

ktmidi = { module = "dev.atsushieno:ktmidi", version = "0.6.2" }

oboe = { module = "com.google.oboe:oboe", version = "1.8.0" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
