[versions]

aap-core = "0.9.4"
aap-lv2 = "0.4.3"

android-compileSdk = "36"
android-minSdk = "29"
android-targetSdk = "36"

androidx-lifecycle = "2.10.0"
accompanist-drawablepainter = "0.37.3"
accompanist-permissions = "0.37.3"
agp = "8.13.2"
kotlin = "2.3.10"
ndk = "29.0.14206865"
cmake = "3.22.1"
build-tools = "35.0.1"
dokka = "2.1.0"
compose-bom = "2026.02.00"
androidx-test = "1.6.2"
coroutines = "1.10.2"
navigation-compose = "2.9.7"
core-ktx = "1.17.0"
appcompat = "1.7.1"
startup-runtime = "1.2.0"
preference-ktx = "1.2.1"
activity-compose = "1.12.4"
webkit = "1.15.0"
junit = "4.13.2"
test-ext-junit = "1.3.0"
espresso = "3.7.0"
oboe = "1.10.0"
ktmidi = "0.11.2"
compose-audio-controls = "0.7.1"

vanniktech-maven-publish = "0.36.0"

[libraries]

aap-core = { module = "org.androidaudioplugin:androidaudioplugin", version.ref = "aap-core" }
aap-midi-device-service = { module = "org.androidaudioplugin:androidaudioplugin-midi-device-service", version.ref = "aap-core" }
aap-ui-compose = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose", version.ref = "aap-core" }
aap-ui-compose-app = { module = "org.androidaudioplugin:androidaudioplugin-ui-compose-app", version.ref = "aap-core" }
aap-ui-web = { module = "org.androidaudioplugin:androidaudioplugin-ui-web", version.ref = "aap-core" }
aap-testing = { module = "org.androidaudioplugin:androidaudioplugin-testing", version.ref = "aap-core" }

aap-lv2 = { module = "org.androidaudioplugin:androidaudioplugin-lv2", version.ref = "aap-lv2" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist-drawablepainter" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
compose-audio-controls = { module = "org.androidaudioplugin:compose-audio-controls", version.ref = "compose-audio-controls" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
libcxx-provider = { module = "dev.atsushieno:libcxx-provider", version.ref = "ndk" }

lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "androidx-lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

junit = { module = "junit:junit", version.ref = "junit" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "test-ext-junit" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

ktmidi = { module = "dev.atsushieno:ktmidi", version.ref = "ktmidi" }

oboe = { module = "com.google.oboe:oboe", version.ref = "oboe" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
