[versions]

aap-core = "0.7.5-pre"

agp = "7.3.1"
kotlin = "1.7.10"
ndk = "25.1.8937393"
build-tools = "33.0.1"
dokka = "1.7.20"
compose = "1.3.1"
androidx-test = "1.4.0"
coroutines = "1.6.4"

[libraries]

tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2022.10.00" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0"}
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
startup-runtime = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

preference-ktx = { module = "androidx.preference:preference-ktx", version = "1.2.0" }
libcxx-provider = { module = "dev.atsushieno:libcxx-provider", version.ref = "ndk" }
material = { module = "com.google.android.material:material", version = "1.7.0" }

lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.5.1" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.6.1" }
webkit = { module = "androidx.webkit:webkit", version = "1.5.0" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

junit = { module = "junit:junit", version = "4.13.2" }
test-core = { module =  "androidx.test:core", version.ref = "androidx-test" }
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.4" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.0" }

ktmidi = { module = "dev.atsushieno:ktmidi", version = "0.4.0" }
mugene = { module = "dev.atsushieno:mugene", version = "0.3.0" }
